= Résumé

*Source content and build scripts for my curriculum vitae (CV), compiled from LaTeX.*

link:https://github.com/kieranpotts/resume/releases/latest[image:https://img.shields.io/github/v/release/kieranpotts/resume?style=flat-square&label=latest&labelColor=%23333333&color=%232266EE[GitHub release]]

== Documentation

=== Requirements

The only requirements are *Docker Desktop* and a good LaTeX editor.

The compilation scripts run in a Docker container, so you do not need to install any LaTeX packages on your host system. The Docker image is based on the `blang/latex` image, which includes a full TeX Live installation.

On Windows, it is RECOMMENDED to configure Docker to use WSL 2, and then run the build commands from WSL in a terminal running under administrator mode. Linux emulators like Git Bash are insufficient.

The script to start the container will run the container under the current user and group. You should add your user to the `docker` group, which will allow you to run Docker commands without needing to use `sudo`.

----
$ sudo usermod -aG docker [your-username]
----

Finally, make sure that each of the `run/*` scripts are executable:

----
$ chmod +x run/*
----

=== Development

To start the Docker container, run:

----
$ ./run/start
----

The start script keeps the container running indefinitely (until it is explicitly stopped), so you can re-run the build command again and again, and each time it will be executed immediately without restarting the container.

To build the résumé to PDF format from the source Tex file, run:

----
$ ./run/build
----

The output file is `./dist/kieran-potts-cv.pdf`.

To stop the Docker container, run:

----
$ ./run/stop
----

=== Releasing

To release a new version of the résumé, simply create a new tag:

----
$ git tag -a v[major].[minor].[patch]
----

It is RECOMMENDED to include details of the changes in the release in a message attached to the Git tag object. If the changes can be summarized in a single line, you can use the `-m` option to specify the message inline:

----
$ git tag -a v2.0.3 -m "Minor edits for improved readability."
----

Otherwise create a temporary release notes file, and use the `-F` option to use the file's contents as the tag message. Release notes SHOULD be formatted using Markdown.

----
$ git tag -a v2.0.3 -F RELEASE_NOTES.md
----

Push the new tag:

----
$ git push origin v2.0.3
----

Alternatively, push any new tags with new commits:

----
$ git push --follow-tags
----

Or you can push commits and tags separately:

----
$ git push
$ git push --tags
----

The release workflow in GitHub Actions will automatically create a release at the tag point, copying across the message from the Git tag. The pipeline will compile the résumé to the PDF format and attach the file to the release. The updated résumé can be downloaded from the https://github.com/kieranpotts/resume/releases[releases page].

== Reference resources

* https://linux.die.net/man/1/pdflatex[pdflatex man page] — The build scripts use `pdflatex` to compile the LaTeX source files into PDF format.

== Acknowledgements

The following resources provided valuable inspiration.

* Andrew Lock's blog post about https://andrewlock.net/building-latex-projects-on-windows-easily-with-docker/[building LaTeX projects with Docker]

* Benedikt Lang's https://github.com/blang/latex-docker/[blang/latex] Docker image

* https://www.overleaf.com/latex/templates/tagged/cv[Overleaf's CV templates]

* https://github.com/posquit0/Awesome-CV[Awesome CV], maintained by Byungjin Park and contributors

* https://github.com/jankapunkt/latexcv[LaTex CV and Résumé Collection], maintained by Jan Küster and contributors

* https://github.com/jakegut/resume[Jake Gutierrez] and https://github.com/lcfyi/software-resume-template[Leslie Cheng's] résumé templates, which are based on https://github.com/sb2nov/resume/[Sourabh Bajaj's]

* Daniil Belyakov's https://github.com/dnl-blkv/mcdowell-cv[McDowell CV], a LuaLaTeX class

* billryan's https://github.com/billryan/resume[résumé template]

* Mark Liu's https://github.com/mliu7/latex-moderncv/[latex-moderncv]

''''

Copyright © 2020-present Kieran Potts, all rights reserved
