= Résumé

*Source content and build scripts for my curriculum vitae (CV), compiled from LaTeX.*

== Documentation

=== Requirements

The compilation scripts run in *Docker Desktop*.

On Windows, it is RECOMMENDED to configure Docker to use WSL 2, and then run the build commands from WSL in a terminal running under administrator mode. Linux emulators like Git Bash are insufficient.

The script to start the container will run the container under the current user and group. You should add your user to the `docker` group, which will allow you to run Docker commands without needing to use `sudo`.

[source,sh]
----
$ sudo usermod -aG docker [your-username]
----

Also, make sure that each of the `run/*` scripts are executable:

[source,sh]
----
$ chmod +x run/*
----

=== Procedure

To start the Docker container, run:

[source,sh]
----
$ ./run/start
----

The start script keeps the container running indefinitely (until it is explicitly stopped), so you can re-run the build command again and again, and each time it will be executed immediately without needing to restart the container.

To build the CV to PDF format from the source Tex file, run:

[source,sh]
----
$ ./run/build
----

The output file is `./dist/kieran-potts-cv.pdf`.

To stop the Docker container, run:

[source,sh]
----
$ ./run/stop
----

== Reference resources

* https://linux.die.net/man/1/pdflatex[pdflatex man page] — The build scripts use `pdflatex` to compile the LaTeX source files into PDF format.

== Acknowledgements

The following resources provided valuable inspiration.

* Benedikt Lang's https://github.com/blang/latex-docker/[blang/latex Docker image] — The build scripts are based on the examples included in this repository

* https://andrewlock.net/building-latex-projects-on-windows-easily-with-docker/[Building LaTeX projects on Windows easily with Docker] by Andrew Lock

* https://www.overleaf.com/latex/templates/tagged/cv[Overleaf CV templates]

* https://github.com/posquit0/Awesome-CV[Awesome CV] — maintained by Byungjin Park and contributors

* https://github.com/jankapunkt/latexcv[LaTex CV and Résumé Collection] — maintained by Jan Küster and contributors

* https://github.com/jakegut/resume[Jake Gutierrez] and https://github.com/lcfyi/software-resume-template[Leslie Cheng's] résumé templates are based on https://github.com/sb2nov/resume/[Sourabh Bajaj's]

* https://github.com/dnl-blkv/mcdowell-cv[Daniil Belyakov's "McDowell CV"], a LuaLaTeX class

* https://github.com/billryan/resume[billryan's résumé template]

* https://github.com/mliu7/latex-moderncv/[Mark Liu's latex-moderncv project]

''''

Copyright © 2020-present Kieran Potts, all rights reserved
